### PR TITLE
ignore probes on CronJobs and enhance pod checks to be aware of the r…

### LINKED ISSUE #108: Ignore CronJob probes
**Describe the bug**
CronJobs are highly likely to not have a readiness or liveness concept as they are typically not hooked up to a service.  It likely makes sense to either ignore them for probes or to have them at a different level or an optional way to disable them.

**To Reproduce**

Have a cron job without a probe and run kube-score

**Expected behavior**
Ability to ignore missing cronjob probes

### PR DESCRIPTION
**Pull request by sstarcher**
…oot type that created them

Resolves #108

### CODE REVIEW

File: score/checks/checks.go [hunk 1]
```diff
@@ -48,7 +49,7 @@ type MetaCheck struct {
 
 type PodCheck struct {
 	ks.Check
-	Fn func(corev1.PodTemplateSpec) scorecard.TestScore
+	Fn func(corev1.PodTemplateSpec, string) scorecard.TestScore
```
Comment (zegl) [inline score/checks/checks.go]: I think that it would be a nice improvement for type safety and clarity if argument this was a `metav1.TypeMeta` instead of a `string`. This also gives the `APIVersion`, which is already relevant (see my other comment on `probes.go`), and likely will be used again in the future.

```suggestion
	Fn func(corev1.PodTemplateSpec, metav1.TypeMeta) scorecard.TestScore
```

File: score/probes/probes.go [hunk 2]
```diff
@@ -16,8 +16,13 @@ func Register(allChecks *checks.Checks, services ks.Services) {
 // ReadinessProbes are not required if the pod is not targeted by a Service.
 //
 // containerProbes takes a slice of all defined Services as input.
-func containerProbes(allServices []corev1.Service) func(corev1.PodTemplateSpec) scorecard.TestScore {
-	return func(podTemplate corev1.PodTemplateSpec) (score scorecard.TestScore) {
+func containerProbes(allServices []corev1.Service) func(corev1.PodTemplateSpec, string) scorecard.TestScore {
+	return func(podTemplate corev1.PodTemplateSpec, kind string) (score scorecard.TestScore) {
+		if kind == "CronJob" {
```
Comment (zegl) [inline score/probes/probes.go]: With the change suggested in  `checks.go`, this could be changed to also check that the object is in the "batch" group, to not cause conflicts with "CronJobs" in other groups, custom or future built in types.

```suggestion
		if typemeta.Kind == "CronJob" && typemeta.GroupVersionKind().Group == "batch")  {
```

**Comment by sstarcher** [comment]
Thanks for the input I'll get those addressed
